package me.ajiew.jithub.base

import androidx.annotation.LayoutRes
import androidx.databinding.ViewDataBinding
import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.module.LoadMoreModule
import com.chad.library.adapter.base.viewholder.BaseDataBindingHolder

/**
 * Extend this adapter to support load more feature
 *
 * @param T type of this adapter's item
 * @param BD ViewDataBinding generated by data binding library, corresponding to the item layout view.
 */
abstract class ListRefreshLoadMoreAdapter<T, BD : ViewDataBinding>(
    @LayoutRes layoutResId: Int
) : BaseQuickAdapter<T, BaseDataBindingHolder<BD>>(layoutResId), LoadMoreModule